### ISSUE TITLE
Source files?

### ISSUE THREAD

**Issue by ghost** [rtlewis88/Solarized-Project#11]
I was interested in forking this repo, do you use any sass sources files to generate css files or do you just hack assets and css directly?

**Comment by romildo** [comment]
I would like to package for [NixOS](https://nixos.org/) some of your themes and it would be nice to have the possibility of building them from source if they are made available.

It would help also to have the names of the themes not changing over time. Releases would be welcome.

**Comment by rtlewis88** [comment]
@caasihaon, both, but it is of course possible to instruct SASS to watch an entire folder with:

sass --watch application/sass:public/stylesheets

In a case where you wish import all your partial files, this should generate one file. In each instance that you edit a file in the folder, the CSS files will be generated automatically.

@romildo, sorry it took so long to get back to you; I am a PhD student - in the throes of my dissertation - and somewhat on auto-pilot. Please email me, for better attention.

**Comment by rtlewis88** [comment]
@caasihaon, both, but it is of course possible to instruct SASS to watch an entire folder with:

sass --watch application/sass:public/stylesheets

In a case where you wish import all your partial files, this should generate one file. In each instance that you edit a file in the folder, the CSS files will be generated automatically.

@romildo, sorry it took so long to get back to you; I am a PhD student - in the throes of my dissertation - and somewhat on auto-pilot. Please email me, for better attention.

**Comment by ghost** [comment]
@rtlewis88 I know how to use  sass, my question was meant to check if you actually provide sass file, cause I could only see CSS files

**Comment by rtlewis88** [comment]
No, I do not provide a sass file.
