### ISSUE TITLE
Arc-Darkest-COLORS custom accent colour

### ISSUE THREAD

**Issue by akemrir** [rtlewis88/Solarized-Project#13]
Can I manage to make own colour variant?
Some input images are rendered? Does all of them has source image?

Does it use any raster images?

**Comment by akemrir** [comment]
Ok. I see mostly svg files.
But what about those png files, where are you generating them?

**Comment by rtlewis88** [comment]
@akemrir, which png files? Thanks :).

**Comment by akemrir** [comment]
gtk 2 assets and xfwm ones
./AD-BlueAgave/gtk-2.0/assets/arrow-up-insens.png
./AD-BlueAgave/xfwm4/right-inactive.png

For example, they need to be prepared from source? right?

**Comment by rtlewis88** [comment]
Once the theme is in existence, I simply convert/change what I need to in Inkscape. You can open the Inkscape image editing program, and then just drag and drop the .PNG file to be converted onto the canvas. Edit the image as needed before saving it as a .SVG file. Click File and select "Save As.". Select "Inkscape SVG" or "Plain SVG" as the file type. Or the opposite. When there is a need to catch up to changes in the GTK ecosystem, I have to start over and create the source.

**Comment by akemrir** [comment]
Ah, I see. I must manually fill those gaps which are needed to be changed with sed for example.
Then in converting process svg -> png they in batch could be updated.
I think simple save as would not help in full automatization of process.

**Comment by rtlewis88** [comment]
;)
