### ISSUE TITLE
KDE System Tray Icons

### ISSUE THREAD

**Issue by twifty** [rtlewis88/Solarized-Project#16]
I've been using your Mango colored icons on KDE for some time now, but one annoyance was the inability to theme the icons displayed in the Systems Taskbar. This is due to two problems:
1. The icons in the taskbar are taken from `~/.local/share/plasma/desktoptheme/[theme name]/icons/` and defaults to `/usr/share/plasma/desktoptheme/[theme name]/icons/` when not found.
2. The icons are not traditional in the sense that each file contains multiple icons each with a unique ID.
3. Some icons cannot easily be themed due to hardcoded paths and/or binary embeded icon resources.

See here: https://techbase.kde.org/Development/Tutorials/Plasma5/ThemeDetails#Theming_Application_Icons_in_the_System_Tray

I have done the hard part of creating svg files that KDE recognizes:
https://github.com/twifty/Material-Black-Mango-Suru-TaskBar

Please feel free to incorporate them into your own project. Some things to note:
1. The file format is near identical to existing icons (except for addition of groups with ID attributes).
2. I've had to create a few new icons where they were either missing or visually incompatible with other icons in the file.
3. Only Mango color scheme is applied, but a "search and replace" of `fill="url(#oomox)"` can easily fix that.
4. All icon sizes (except for `osd.svg`) are 16px (KDE will resize depending on taskbar/DPI size).
5. Important - Inkscape fails to render correctly!

Regarding Inkscape: Many of the files use `<use href="#sth" />`, Inkscape can only render `<use xlink:href="#sth" />` and KDE can only render the former.

**Comment by rtlewis88** [comment]
We always appreciate anything KDE/Qt folks can do to move things along, for relevant users. Notwithstanding, we offer no involvement in projects outside the GTK ecosystem.
Best of luck and kindest regards,
rtl88Themes
