### ISSUE TITLE
Ubuntu 20.04 separater too large

### ISSUE THREAD

**Issue by bluefangs** [rtlewis88/Solarized-Project#17]
I got the latest version from [here](https://www.gnome-look.org/p/1317409/) and moved the files to /usr/share/themes/Arc-Darkest.

I noticed that some of the elements are rendering with weird padding issues. Please refer to the screenshots. How do I fix this?

Thanks.

![Screenshot from 2020-04-24 20-10-40](https://user-images.githubusercontent.com/19926675/80224998-1da08000-8668-11ea-9fd4-b272b8514998.png)
![Screenshot from 2020-04-24 20-11-06](https://user-images.githubusercontent.com/19926675/80225007-1f6a4380-8668-11ea-8c2d-34489f51fcc5.png)
![Screenshot from 2020-04-24 20-11-23](https://user-images.githubusercontent.com/19926675/80225011-2002da00-8668-11ea-9ff8-5859db7bd69d.png)

**Comment by rtlewis88** [comment]
That has only happened to users who do not download the correct version for their GTK operating system. Any user who has had that issue has remedied it by downloading the supplied variant for the latest GTK operating systems, i.e., the "3.36" download zip-file - and not the variant for earlier GTK operating systems.  Regards, rtl88Theme member.
