### ISSUE TITLE
Repo size reduction

### ISSUE THREAD

**Issue by AnwarShah** [rtlewis88/Solarized-Project#19]
Currently the repository size is huge. Can you reduce the size by truncating history. Since many of the commits are just upload as far as I see. 

I've cloned the repository and switching to braches become real headache.

**Comment by rtlewis88** [comment]
I'll have a team member look into doing that soon. There are too many people involved in these themes to arbitrarily truncate the history. They will have to all be polled, to find out who needs a saved log for there reference, etc. We hope you can utilize what you need either way. Thank you for the feedback.

**Comment by AnwarShah** [comment]
Ok, got it. Hope the issue will be taken into account soon.
