### ISSUE TITLE
Hard to tell which checkbox is checked in GTK3 applications

### ISSUE THREAD

**Issue by caspear** [rtlewis88/Solarized-Project#2]
Using 1.2 release of Punk-Ozone-GTK

![checkbox](https://user-images.githubusercontent.com/1940324/61353835-a46a3600-a868-11e9-8407-94f37703850c.png)

**Comment by janith-dev** [comment]
Using Theme Version - 1.4.2 
OS - POP OS 19.04

#### Google Chrome (With Google Dark Theme)
***With Other Theme***
![Chrome - FR](https://user-images.githubusercontent.com/9546456/63654302-e781c800-c789-11e9-9423-01cf714667e8.png)
***With Punk Theme***
![Chrome - Punk](https://user-images.githubusercontent.com/9546456/63654303-ed77a900-c789-11e9-9707-d17a60da8b25.png)
#### File Manager
***With Other Theme***
![FM - FR](https://user-images.githubusercontent.com/9546456/63654308-f799a780-c789-11e9-8aae-a38bd6116ec8.png)
***With Punk Theme***
![FM - Punk](https://user-images.githubusercontent.com/9546456/63654311-f9fc0180-c789-11e9-9dd9-69c74bdf2fc2.png)
#### VS Coder (Warning)
***With Other Theme***
![VS Code - FR](https://user-images.githubusercontent.com/9546456/63654313-fbc5c500-c789-11e9-8950-1b0bb588bce9.png)
***With Punk Theme***
![VS Code - Punk](https://user-images.githubusercontent.com/9546456/63654314-fd8f8880-c789-11e9-9a5e-aa8330a1c899.png)
#### Gnome Extension - Activities Configurator
***With Other Theme***
![AC - FR](https://user-images.githubusercontent.com/9546456/63654318-06805a00-c78a-11e9-813a-1e3d507173e2.png)
***With Punk Theme***
![AC - Punk](https://user-images.githubusercontent.com/9546456/63654319-08e2b400-c78a-11e9-8b02-ceca757dde3d.png)

Hope this will help to fix the check box issue
