### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by FredericGuilbault** [rtlewis88/Solarized-Project#20]
Hi, I have few missing Icons for my project. 
May I request Icons for : 

OpenCPN https://opencpn.org/
SignalK http://signalk.org/
ZyGrib https://framalibre.org/sites/default/files/styles/thumbnail/public/leslogos/logo_zygrib_0.jpg

For Abyss-DEEP-Suru-GLOW

**Comment by rtlewis88** [comment]
Here you go; enjoy! :) 

If any of them do not show up - let me know; and I'll stick them a few more places.

[Frederic's_Abyss-DEEP-Suru-GLOW.zip](https://github.com/rtlewis88/rtl88-Themes/files/4566461/Frederic.s_Abyss-DEEP-Suru-GLOW.zip)

**Comment by FredericGuilbault** [comment]
Wow, that was fast :D  
Sadly I think it's not the good zip. I can't find the files 

![find](https://user-images.githubusercontent.com/37122999/80870716-6236a780-8c76-11ea-9df4-c0d4e66d2109.png)

At the end it's to pack in https://github.com/lysmarine/lysmarine_gen build script with a git pull. I can wait the commit.

**Comment by rtlewis88** [comment]
Let's try this again...
[Frederic's-Custom_Abyss-DEEP-Suru-GLOWAbyss-DEEP-Suru-GLOW.zip](https://github.com/rtlewis88/rtl88-Themes/files/4571084/Frederic.s-Custom_Abyss-DEEP-Suru-GLOWAbyss-DEEP-Suru-GLOW.zip)
