### ISSUE TITLE
Solarized-Dark-GNOME-Shell-2020 [also support for GS-3.36] Is a compact version possible?

### ISSUE THREAD

**Issue by IvanDeFelice76** [rtlewis88/Solarized-Project#23]
Solarized-Dark-GNOME-Shell-2020 [also support for GS-3.36] 

Is it possible to have a compact Blue version for small monitors with a not too dark gtk included?

**Comment by rtlewis88** [comment]
It should already be compact; I will have someone look into it, and get back.

**Comment by IvanDeFelice76** [comment]
> It should already be compact; I will have someone look into it, and get back.

![Schermata da 2020-05-07 15-21-42](https://user-images.githubusercontent.com/26720956/81299415-7b749500-9076-11ea-934c-3fc2bb8f4ed8.png)

If possible reduce the size and a Gtk theme for folders etc..

Personally I would eliminate dividing lines in menus that just clash, they are useless!

![Schermata da 2020-05-07 15-22-30](https://user-images.githubusercontent.com/26720956/81299728-f0e06580-9076-11ea-9b35-e4cf4d45ddbc.png)

If possible, otherwise splendid theme

**Comment by rtlewis88** [comment]
By the pics, you have the wrong version installed. Try the other other one (not the 3.36)

**Comment by IvanDeFelice76** [comment]
> By the pics, you have the wrong version installed. [ Dalle immagini, hai installato la versione sbagliata.] Try the other other one (not the 3.36) [ Prova l'altro (non il 3.36)]

I have Fedora 32 with GNOME Shell 3.36.2 

Which one should I use then?

**Comment by IvanDeFelice76** [comment]
> By the pics, you have the wrong version installed. Try the other other one (not the 3.36)

Yes better, but insert a Gtk for the Cian version and if possible a compact version for small monitors maybe with calendar and notifications a bit reduced please
