### ISSUE TITLE
Missing checkboxes in Material-Solarized

### ISSUE THREAD

**Issue by secuvim** [rtlewis88/Solarized-Project#5]
Checkboxes are not displayed in gtk applications. 

The example shows two checkboxes not displayed for `Show Hidden Files` and the `Sidebar` toggle in nautilus (gnome-files 3.32). 
![Screenshot from 2019-08-08 13-07-29](https://user-images.githubusercontent.com/11874296/62698962-a8f4bb00-b9de-11e9-8f4f-9fb8c152ced2.png)

The debugging grid shows the empty tiles.
![Screenshot from 2019-08-08 13-09-34](https://user-images.githubusercontent.com/11874296/62698961-a8f4bb00-b9de-11e9-818a-dda99ae41d4b.png)

I am running:
* GNOME 3.32.2
* gtk3 1:3.24.10-1
* gtk2 2.24.32-1
* gtk-engines 2.21.0-4 
* gtk-engine-murrine 0.98.2-3.

I really like the theme so far. But the missing checkbox feature is a dealbreaker for me. Please let me know if I can assist in any way to resolve the issue.

**Comment by blue995** [comment]
Same issue in "Ultimate-Plata-Dark" and "Ultimate-Plata-Dark-GTK-Less-Indigo".
Works in "Budgie-Ultimate-Plata-Dark" though

- Xfce 4.14
- gtk 3.24.10-1
- gtk 2.24.32-1
- gtk-xfce-engine 2.10.1-2
- gtk-engine-murrine 0.98.2-3

**Comment by secuvim** [comment]
Budgie-Ultimate-Plata-Dark ist based directly on the arc theme. See the file gtk-3.0/gtk.css:
`@import url("resource:///org/gnome/arc-theme/gtk-main.css");`

I haven't figured out what is wrong with the gtk.css file in the other themes.

**Comment by secuvim** [comment]
I managed to fix the issue on my system by adding the following modifications to the gtk-3.0/gtk.css file:

```
popover modelbutton.flat check:not(:checked):not(:indeterminate):not(:disabled) {
  -gtk-icon-source: -gtk-icontheme("checkbox-symbolic");
}

popover modelbutton.flat check:checked:not(:indeterminate):not(:disabled) {
  -gtk-icon-source: -gtk-icontheme("checkbox-checked-symbolic");
}

popover modelbutton.flat
radio:not(:checked):not(:indeterminate):not(:disabled) {
  -gtk-icon-source: -gtk-icontheme("radio-symbolic");
}

popover modelbutton.flat
radio:checked:not(:indeterminate):not(:disabled) {
  -gtk-icon-source: -gtk-icontheme("radio-checked-symbolic");
}
```

**Comment by rtlewis88** [comment]
Thank you very much; I'm putting the fix out now.

**Comment by secuvim** [comment]
Please reopen this issue as a working fix was not merged.
Did any complications arise with the proposed solution?
