### ISSUE TITLE
why is it so big ?

### ISSUE THREAD

**Issue by Krafting** [rtlewis88/Solarized-Project#7]
Theme: Arc Darkest

On cinnamon, why the preview is so big ?
Is the theme really like that ? because it's not that great :(

![image](https://user-images.githubusercontent.com/36538123/63551720-215a9080-c536-11e9-849b-9a6b0346fa68.png)

also, any plan on a normal version (just dark and not darkest?)

**Comment by rtlewis88** [comment]
Everything's a work in progress; I'll get to all of that.

**Comment by Krafting** [comment]
Okey! thanks for your answer :)

have a nice day
